// Generate the baseline variant scene file with the same usage shape as the
// selector-leaf variant but using the current MessageKeys<NestedKeyOf<>> approach.
// The selector-leaf variant is generated by gen-selector-leaf.mjs.
import { readFileSync, writeFileSync } from "node:fs";
const sample = JSON.parse(readFileSync("sample-keys.json", "utf8"));
const N = sample.length;

function callSitesString(getKeyExpr) {
	const lines = [];
	for (let i = 0; i < N; i++) {
		lines.push(`takesKey(${getKeyExpr(i)});`);
		lines.push(`t(${getKeyExpr(i)});`);
		lines.push(`tFn(${getKeyExpr(i)});`);
	}
	return lines.join("\n");
}

const HEADER = `// SPDX: variant scene for tsgo TS2590 + perf testbed.\nimport messages from "./fixture.json";\ntype Messages = typeof messages;\ntype TranslationValues = Record<string, string | number>;\n`;

// --- baseline (current production approach) ---
{
	const code = HEADER + `
type NestedKeyOf<ObjectType> = ObjectType extends object
	? { [P in keyof ObjectType]: \`\${P & string}\` | \`\${P & string}.\${NestedKeyOf<ObjectType[P]>}\` }[keyof ObjectType]
	: never;
type NestedValueOf<ObjectType, Path extends string> = Path extends \`\${infer Cur}.\${infer Rest}\`
	? Cur extends keyof ObjectType ? NestedValueOf<ObjectType[Cur], Rest> : never
	: Path extends keyof ObjectType ? ObjectType[Path] : never;
type MessageKeys<ObjectType, AllKeys extends string> = {
	[P in AllKeys]: NestedValueOf<ObjectType, P> extends string ? P : never;
}[AllKeys];

export type BigUnion = MessageKeys<Messages, NestedKeyOf<Messages>>;

declare function takesKey(label: BigUnion): void;
declare function t(key: BigUnion, values?: TranslationValues): string;
declare function getTranslationProps(input: BigUnion | [BigUnion, TranslationValues]): [BigUnion, TranslationValues | undefined];
declare function useTranslations(): { (key: BigUnion): string; (key: BigUnion, values: TranslationValues): string };

const tFn = useTranslations();

` + callSitesString(i => JSON.stringify(sample[i])) + `

declare const k1: BigUnion;
declare const k2: BigUnion;
export const arr = [k1, k2]; // TS2590 trigger under tsgo
export const tuple: [BigUnion, TranslationValues] = ["${sample[0]}", { v: "x" }];
`;
	writeFileSync("repro-baseline.ts", code);
}

console.log("wrote repro-baseline.ts");
