// Minimal reproduction of a type-check divergence between tsc and tsgo.
//
// tsgo reports TS2590 on a bare array literal containing three values of a
// large string-literal union. tsc@6.0.2 accepts the same input.
//
// Run:
//   pnpm install --ignore-workspace
//   pnpm run tsc     # exit 0
//   pnpm run tsgo    # exit 2 — TS2590 at the array literal below

// NestedKeyOf / NestedValueOf / MessageKeys copied from
// use-intl/dist/types/core/MessageKeys.d.ts (no runtime dependency needed).

type NestedKeyOf<ObjectType> = ObjectType extends object
	? {
			[Property in keyof ObjectType]:
				| `${Property & string}`
				| `${Property & string}.${NestedKeyOf<ObjectType[Property]>}`;
		}[keyof ObjectType]
	: never;

type NestedValueOf<ObjectType, Path extends string> = Path extends `${infer Cur}.${infer Rest}`
	? Cur extends keyof ObjectType
		? NestedValueOf<ObjectType[Cur], Rest>
		: never
	: Path extends keyof ObjectType
		? ObjectType[Path]
		: never;

type MessageKeys<ObjectType, AllKeys extends string> = {
	[PropertyPath in AllKeys]: NestedValueOf<ObjectType, PropertyPath> extends string ? PropertyPath : never;
}[AllKeys];

// fixture.json is an anonymized translation fixture with 7 161 leaf keys and
// max nesting depth 9. Generated by scramble.mjs from the original en.json.
import messages from "./fixture.json";
type Messages = typeof messages;

type BigUnion = MessageKeys<Messages, NestedKeyOf<Messages>>;

declare const key1: BigUnion;
declare const key2: BigUnion;

// tsgo: TS2590 here. tsc@6.0.2: clean.
export const arr = [key1, key2];
